### ISSUE TITLE
Git tag 1.8.13 exists, but missing on rubygems.org / in CHANGELOG.md

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-resource_api#266]
## Describe the Bug

Hi, I noticed that the tag `1.8.13` exists. but it's not available on rubygems.org and not in the CHANGELOG.md. 

## Expected Behavior

I expect that rubygems.org versions / changelog entries / git tags match

## Additional Context

I'm not sure what's wrong here. Maybe the tag was created by accident? Or did you forget to push the release?

**Comment by DavidS** [comment]
I've manually updated the changelog in #268 and also manually pushed the release to rubygems. The release team assured me changes to their process to avoid this problem going forward.
