### ISSUE TITLE
Resource purging does not work with simple_get_filter

### ISSUE THREAD

**Issue by seanmil** [puppetlabs/puppet-resource_api#303]
## Describe the Bug

For types with the `simple_get_filter` feature it is seemingly not possible to perform resource purging with either the `resources` type or the `purge` type from crayfishx/purge.

When attempting to purge types with `simple_get_filter` it seems that the existing-but-unmanaged resources are never found via the type instances() method, therefore preventing them from being purged.

Removing the `simple_get_filter` flag is sufficient to restore resource purging to a working state.

## Expected Behavior

Types using `simple_get_filter` should support instantiation, even of unknown resources, via instances() OR a warning/error should be thrown.  The user of a given Resource API-based resource should not have to be aware of the implementation details to figure out if resource purging will work.

## Environment
 - Version Puppet 7.18.0

**Comment by seanmil** [comment]
So, doing a bit more digging, per the [Puppet Specifications on the Resource API](https://github.com/puppetlabs/puppet-specifications/blob/master/language/resource-api/README.md#provider-feature-simple_get_filter):

> Some resources are very expensive to enumerate. The provider can implement simple_get_filter to signal extended capabilities of the get method to address this. The provider's get method will be called with an array of resource names, or nil. The get method must at least return the resources mentioned in the names array, but may return more than those. If the names parameter is nil, all existing resources should be returned. The names parameter defaults to nil to allow simple runtimes to ignore this feature.

However, the resource API doesn't pass `nil`, it passes `[]` https://github.com/puppetlabs/puppet-resource_api/blob/main/lib/puppet/resource_api.rb#L234

I think switching `[]` to `nil` here should be sufficient.

**Comment by LukasAud** [comment]
Issue potentially addressed by #304

**Comment by LukasAud** [comment]
Hi @seanmil, can you confirm whether this issue was addressed by the aforementioned Pull Request? If so, we would like to close this thread.

**Comment by jordanbreen28** [comment]
inline with above comments. please re-open if necessary
