### ISSUE TITLE
Munging fails on Integer data type when passed value is an integer or a float

### ISSUE THREAD

**Issue by hajee** [puppetlabs/puppet-resource_api#314]
## Munging fails on Integer data type when passed value is an integer or a float

In Ruby 3.2, the Integer and float data type no longer supports the `=~` operator. Causing correct values passed to te munger to fail.

Running the unit tests on Ruby 3.2 shows all these errors. The log is attached to this issue.

## Environment
 - Version: When running Puppet 8 on Ruby 3.2
 - Platform All

## Additional Context
[unit-test.log](https://github.com/puppetlabs/puppet-resource_api/files/11372295/unit-test.log)

**Comment by hajee** [comment]
@cthorn42 Is this software still actively maintained by Puppet? It needs some adjusting for use with Puppet 8. Is that planned?

**Comment by hajee** [comment]
I would really appreciate it if somebody told me what the plans are for this gem. I would guess that a lot of custom types that are built using this gem will fail on Ruby 3.2 and thus Puppet8. So I would guess somebody at Perforce/Puppet would have a plan for this?

**Comment by cthorn42** [comment]
@hajee I'm sorry I didn't get back to you earlier, I was out of the office when you initially pinged me on this ticket. 
I created a ticket in our system, https://tickets.puppetlabs.com/browse/PUP-11866, to track this issue. 
I don't have an expected timeline but this issue is now on our radar. Thank you for reporting this.

**Comment by jordanbreen28** [comment]
Closed in https://github.com/puppetlabs/puppet-resource_api/pull/317 and released in v1.8.18
