### ISSUE TITLE
Provider using canonicalize feature not working anymore with puppet 8 

### ISSUE THREAD

**Issue by torstenfohrer** [puppetlabs/puppet-resource_api#315]
## Describe the Bug
If anyone implements a provider/type pair with feature canonicalize enabled,they cannot anymore change any attribute values

## Expected Behavior
resource api framework accept changed values, and be only strict that implementation of canonicalize method doesn't change input values.

## Steps to Reproduce
1. Implement simple provider and try to change any attribute
2. 

## Environment
 - Puppet OSS 8.0.1
 - Bundled Resource Api 1.18.6

**Comment by jordanbreen28** [comment]
hey @torstenfohrer thanks for raising this!
Could you add a little more info to the issue if possible, something like the below would really help to replicate this.

1. Small snippet of your type implementation
2. Your canonicalize method
3. logs from a puppet run which describe the strange behaviour (if applicable)

Thanks again.

**Comment by jordanbreen28** [comment]
Please re-open when necessary!
